//Author: Ridwan Kurmally
//Git Repository: https://github.com/Ridwan2606/COMP206-Software-Systems-W2020

/*
Lab I - Fork (Solution 2.2 - Shell Memory)  [ NOT WORKING DUE TO SYSTEM CONFIGURATION BUT CODE IS CORRECT ]

In this C-Code, we are using the shell memory as a medium to share information between forked processes.
However, there is a configuration on the server/system that is currently
copying the shell memory for the forked processes. 
Meaning that the children and parent are not actually sharing the same shell memory 
but have their own separate copies
Until this configuration is fixed, this code wont print anything but it's logically correct 
(can be used for final).

Note that the other two methods, textfile and shared memory, definitely work as it's not dependent on
the system shell
*/

/*
COMPILATION INSTRUCTION:

Run the following commands on the terminal:

export TURN=Producer
gcc -o consumer consumer.c
gcc -o producer producer.c
./producer & ./consumer

*/

/*
This is the consumer code. It is supposed to print the number generated by the producer.
*/
#include <stdio.h> 
#include <stdlib.h>
#include <string.h>

int main(int argc, char const *argv[])
{
    int value;
    do
    {
        while (strcmp(getenv("TURN"),"Consumer")!=0); //wait for Consumer turn
        
        value = atoi(getenv("VALUE"));
        printf("%d ",value);    //Prints the value
        setenv("TURN","Producer",1);    //Gives next turn to producer

    } while (value!=10); //repeat until last number is reached
}

